# Generated by Django 5.1.1 on 2024-11-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='time',
            field=models.CharField(default='00:00', max_length=10),
        ),
    ]
