# Generated by Django 5.1.1 on 2024-11-16 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
